version: '3'

vars:
  BINARY_NAME: sitecheck
  SOURCE_NAME: sitecheck.go
  INSTALL_PATH: "{{.HOME}}/bin"

tasks:

  default:
    desc: Show available tasks
    cmds:
      - task --list

  scan:
    desc: Run staticcheck
    cmds:
      - staticcheck {{.SOURCE_NAME}}

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run {{.SOURCE_NAME}}

  build:
    desc: Build binary
    cmds:
      - go build -o {{.BINARY_NAME}} {{.SOURCE_NAME}}

  install:
    desc: Build and install to ~/bin
    deps: [build]
    cmds:
      - mkdir -p {{.INSTALL_PATH}}
      - cp {{.BINARY_NAME}} {{.INSTALL_PATH}}/

  run:
    desc: Build and run binary
    deps: [build]
    cmds:
      - ./{{.BINARY_NAME}} {{.CLI_ARGS}}

  deploy:
    desc: Scan, lint, build, install
    deps: [scan, lint, install]

  clean:
    desc: Remove built binaries
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f {{.INSTALL_PATH}}/{{.BINARY_NAME}}
